title: CrakinDev
description: Content update coming shortly

# Build Settings
plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: Crakin17
    github: CrakinDev
    linkedin: Noel Hanna

    youtube: CrakinDev
    youtube_channel: UC7lYOjels3A_sw6g5f6Xyfg
    youtube_channel_name: CrakinDev
markdown: kramdown
