title: CrakinDev
description: Content update coming shortly

# Build Settings
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes@4.22.0

minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
